2025-07-13 22:47:30,534 - INFO - Starting scrape for channel: https://t.me/lobelia4cosmetics
2025-07-13 22:47:30,535 - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-07-13 22:47:30,681 - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-07-13 22:47:31,013 - INFO - System clock is wrong, set time offset to -72s
2025-07-13 22:47:32,934 - ERROR - Error scraping https://t.me/lobelia4cosmetics: Object of type datetime is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\Hiwi\telegramMedicalInsights\src\scraping\scrape.py", line 41, in scrape_channel
    json.dump(raw_messages, f, ensure_ascii=False, indent=2)
  File "C:\Users\Hiwi\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Hiwi\anaconda3\Lib\json\encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "C:\Users\Hiwi\anaconda3\Lib\json\encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "C:\Users\Hiwi\anaconda3\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\Users\Hiwi\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Hiwi\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
2025-07-13 22:47:33,009 - INFO - Starting scrape for channel: https://t.me/tikvahpharma
2025-07-13 22:47:34,259 - ERROR - Error scraping https://t.me/tikvahpharma: Object of type datetime is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\Hiwi\telegramMedicalInsights\src\scraping\scrape.py", line 41, in scrape_channel
    json.dump(raw_messages, f, ensure_ascii=False, indent=2)
  File "C:\Users\Hiwi\anaconda3\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Hiwi\anaconda3\Lib\json\encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "C:\Users\Hiwi\anaconda3\Lib\json\encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "C:\Users\Hiwi\anaconda3\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\Users\Hiwi\anaconda3\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\Hiwi\anaconda3\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
